### ISSUE TITLE
Updated OC EFI for Big Sur

### ISSUE THREAD

**Issue by CytoStorm** [cstrouse/Dell-PowerEdge-T30-Hackintosh#2]
Hey there,

Any luck updating OpenCore and getting Big Sur running on this? I have a working 10.15.7 installation using Clover, but would love to update this system to OpenCore. I assume 11.1 would require at least OC 0.6.4 and maybe some config changes? Just wanted to see if you were able to keep updating.

Thanks!

**Comment by cstrouse** [comment]
I bought an M1 Air and haven't done much with the machine since then. IIRC I was able to update directly to Big Sur. If I get some time this week I will update the repo.

**Comment by cstrouse** [comment]
I just updated this with the setup I've been using since the Big Sur update. I don't have time to do the updates right now to get the kexts, OC, and macOS current but this should get you upgraded.

**Comment by cstrouse** [comment]
@CytoStorm Were you able to update to Big Sur? If I don't hear from you in the next few days I will be closing this issue.

**Comment by CytoStorm** [comment]
Thanks Casey! I actually started running Xpenology on my T30, but am still intending to try this out when I get the spare time. Just wanted confirmation that I can run Big Sur with the included version of OC... I know updating it can be a hassle between versions. Thanks again! I’ll update this or add a comment when I try installing again.

**Comment by cstrouse** [comment]
Sure. I just updated to OC 0.6.7 and Big Sur 11.2.3 so I'll be uploading the current EFI sometime today.
