### ISSUE TITLE
Monterey Support

### ISSUE THREAD

**Issue by Allanrfox** [cstrouse/Dell-PowerEdge-T30-Hackintosh#6]
Hey man good morning (11:13am my time) I would like to ask you a question since you're running iGPU only like I am, If you have gotten Monterey to display, im using my own EFI still but when xnu finsishes up and then the apple logo is supposed to show up my monitor looses signal, I would like to ask if you have tried to get Monterey running.

-Allan Fox

**Comment by Allanrfox** [comment]
I have mixed and matched device properties and still the same result

**Comment by swanduron** [comment]
I supposed that the OpenCore and drivers (e.g. whatever Green) need to be upgraded. Sometimes, the dGPU is easy to exempt the troubles of macOS upgrading, and I suggest installing a dedicated display card to avoid those problems.

In other words, I install Monterey on my other desktop computer (with Gen10 Intel CPU), the sleep/wake-up function got me crazy right now: the system stuck into the black screen randomly. Since the Monterey is not a public version, we may able to wait for it.

**Comment by Allanrfox** [comment]
Oh yeah I've definitely updated all of my drivers, kexts and OC, all latest release but I still get that issue

**Comment by Allanrfox** [comment]
Alright then, I'll look into getting an RX580, also quick question, is the M.2 slot still locked on BIOS version 1.6.0? Since I see you have an NVME drive listed in your specs, did Dell finally give in, or did you use a modified grub shell to unlock it too?

**Comment by swanduron** [comment]
I took photos from the BIOS setting, please refer to them. My BIOS is 2.13.1

![IMG_8710](https://user-images.githubusercontent.com/16800281/134747140-5a0635b9-f223-4e83-9db6-07b20ee6c1cf.JPG)
.
![IMG_8711](https://user-images.githubusercontent.com/16800281/134747146-6c730d53-7c87-4394-8d8e-d7ba1244ad44.JPG)

**Comment by Allanrfox** [comment]
Hey that's a Dell Precision tower though?, I'm asking about the PowerEdge T30 lol

**Comment by Allanrfox** [comment]
Latest BIOS for thr machine is 1.6.0

**Comment by Allanrfox** [comment]
I can now happily close this issue since I have now gotten Monterey to display, gonna install now, had to use a modded grub shell and do some iGPU stuff

**Comment by cstrouse** [comment]
@Allanrfox The T30 and Precision T3620 are the same machine with the only differences being restrictions in the UEFI. I had both a T30 and T3620 with full functionality thanks to this method for flashing the Precision UEFI onto the T30 motherboard (https://networkcookbook.com/2021/05/flashing-dell-poweredge-t30-to-precision-t3620/
