### ISSUE TITLE
Schdule of support macOS 12 Monterey

### ISSUE THREAD

**Issue by swanduron** [cstrouse/Dell-PowerEdge-T30-Hackintosh#7]
Hello bro,

Do you have a plan to shift your EFI file to the newest OC and support macOS 12 Monterey? This is just a request from my personal side and only see whether you are available recently.

**Comment by cstrouse** [comment]
I've been using an M1 MacBook Air for the last year and a new custom hack instead of the Dells. If you're willing to do the testing I'd be OK with updating the EFI for you but no longer have a complete T3620/T30 to test with.

**Comment by swanduron** [comment]
Could you share your new chassis here? I also want to buy a new powerful computer in my home. To be honest, my  T3620 may retire in the next 1 or 2 years and I am planning to move it to my office as labor machine which is used to compile code.

If possible, could you make a new repo for your new chassis? I am very thanks for your help in EFI of T3620, it works very smoothly and I feel no different with my OOOOOLD Mac Pro "Trash".

Of course, it's OK if you are busy or you don't want to share your new EFI. The T3620 works with me a lot of time and it seems that it can hold on to the next Mac Pro I can afford. Lol.
